# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
name: Upload Python Package

on:
  push:
    tags: "*"
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
        
    - name: Install dependencies
      run: poetry install
      
    - name: Build package
      run: poetry build
      
    - name: Publish package
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_SECRET_TOKEN }}
      run: |
        # set the token
        poetry config pypi-token.pypi $PYPI_TOKEN
        # publish package
        poetry publish
